apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-07-19T12:02:42Z"
  generateName: pd-disaggregation-nvidia-gpu-vllm-decode-5f467446bd-
  generation: 1
  labels:
    inference.networking.k8s.io/engine-type: vllm
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: pd-disaggregation
    llm-d.ai/model: gpt-oss-120b
    llm-d.ai/role: decode
    pod-template-hash: 5f467446bd
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "38"
  name: pd-disaggregation-nvidia-gpu-vllm-decode-5f467446bd-dzbcw
  namespace: dpikus-pd-sglang-bench
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pd-disaggregation-nvidia-gpu-vllm-decode-5f467446bd
    uid: 56c3d982-2685-4d06-ab95-3c1950bd720f
  resourceVersion: "33216355"
  uid: ba3ac39f-2847-40d5-aa1e-76a0ad19ba8b
spec:
  containers:
  - args:
    - Qwen/Qwen3-VL-235B-A22B-Instruct
    - --disable-access-log-for-endpoints=/health,/metrics,/v1/models
    - --tensor-parallel-size=8
    - --block-size=128
    - --kv-transfer-config
    - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    - --no-disable-hybrid-kv-cache-manager
    - --port=8200
    - --load-format=runai_streamer
    command:
    - vllm
    - serve
    env:
    - name: HF_HUB_OFFLINE
      value: "1"
    - name: TRANSFORMERS_OFFLINE
      value: "1"
    - name: HF_HOME
      value: /model-cache
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          key: HF_TOKEN
          name: llm-d-hf-token
          optional: true
    - name: RUNAI_STREAMER_MEMORY_LIMIT
      value: "17179869184"
    - name: VLLM_NIXL_SIDE_CHANNEL_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: modelserver
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: modelserver
    ports:
    - containerPort: 8200
      name: modelserver
      protocol: TCP
    - containerPort: 5600
      name: nixl
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
    startupProbe:
      failureThreshold: 120
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - --port=8000
    - --vllm-port=8200
    - --connector=nixlv2
    - --zap-log-level=1
    - --secure-proxy=false
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.8.0
    imagePullPolicy: Always
    name: routing-proxy
    ports:
    - containerPort: 8000
      name: sidecar
      protocol: TCP
    resources: {}
    restartPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: gc37cba
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pd-disaggregation-nvidia-gpu-vllm-sa
  serviceAccountName: pd-disaggregation-nvidia-gpu-vllm-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: model-cache
    persistentVolumeClaim:
      claimName: llm-d-model-cache
  - emptyDir:
      medium: Memory
      sizeLimit: 20Gi
    name: shm
  - emptyDir: {}
    name: torch-compile-cache
  - emptyDir: {}
    name: vllm-config
  - emptyDir: {}
    name: triton-cache
status:
  allocatedResources:
    cpu: "16"
    memory: 256Gi
    nvidia.com/gpu: "8"
    rdma/ib: "1"
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T12:02:57Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T12:02:58Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T12:13:27Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T12:13:27Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T12:02:56Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "16"
      memory: 256Gi
      nvidia.com/gpu: "8"
      rdma/ib: "1"
    allocatedResourcesStatus:
    - name: nvidia.com/gpu
      resources:
      - health: Healthy
        resourceID: GPU-58f1d71a-7a32-d1a9-ba60-9b2eb9ca01f6
      - health: Healthy
        resourceID: GPU-8f301f2e-a801-65f6-0651-8571628b84e3
      - health: Healthy
        resourceID: GPU-7d3b787a-f56b-5ba7-3cc6-835f17d32ed2
      - health: Healthy
        resourceID: GPU-3f0b869e-db26-96a6-e92a-453d522c642c
      - health: Healthy
        resourceID: GPU-7aba44b9-29eb-96ae-a3f3-56024a23055a
      - health: Healthy
        resourceID: GPU-ac6c1402-739e-cbf2-7da2-130ec2dc2608
      - health: Healthy
        resourceID: GPU-c313468d-cf4c-4203-5caf-9638b991b14a
      - health: Healthy
        resourceID: GPU-65a71e87-caaf-761b-4163-8bfdc6079a64
    - name: rdma/ib
      resources:
      - health: Healthy
        resourceID: "30"
    containerID: containerd://e5214fcaefa16522ddb7035155a23c3137f1d722483b0b8dbfaec9f12f2e6eca
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imageID: ghcr.io/revit13/vllm-openai@sha256:ac60d4876f3eb8d888903b97bcc55bbbfd4a77d45f73155606f404358cccecab
    lastState: {}
    name: modelserver
    ready: true
    resources:
      limits:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-19T12:02:58Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
  hostIP: 10.202.206.123
  hostIPs:
  - ip: 10.202.206.123
  initContainerStatuses:
  - containerID: containerd://609a46674b2072a7ce7ec7dc42aa068c421785b20f84b0173529b8aceae0a83f
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.8.0
    imageID: ghcr.io/llm-d/llm-d-routing-sidecar@sha256:d49dd8d7d6a15a4ef82f3aaa322783ebaead2bf9fc9cdb4d375da0da12bf0147
    lastState: {}
    name: routing-proxy
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-19T12:02:58Z"
    user:
      linux:
        gid: 65532
        supplementalGroups:
        - 65532
        uid: 65532
  observedGeneration: 1
  phase: Running
  podIP: 10.0.6.147
  podIPs:
  - ip: 10.0.6.147
  qosClass: Burstable
  resources:
    limits:
      cpu: "16"
      memory: 256Gi
    requests:
      cpu: 15978m
      memory: 256Gi
  startTime: "2026-07-19T12:02:56Z"
