apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-07-17T08:48:22Z"
  generateName: pd-disaggregation-nvidia-gpu-vllm-prefill-9fb48dc8f-
  generation: 1
  labels:
    inference.networking.k8s.io/engine-type: vllm
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: pd-disaggregation
    llm-d.ai/model: gpt-oss-120b
    llm-d.ai/role: prefill
    pod-template-hash: 9fb48dc8f
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "82"
  name: pd-disaggregation-nvidia-gpu-vllm-prefill-9fb48dc8f-tkxcv
  namespace: dpikus-pd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pd-disaggregation-nvidia-gpu-vllm-prefill-9fb48dc8f
    uid: aa6f3793-7cfe-4c25-a438-3b6a7ef50463
  resourceVersion: "31054189"
  uid: df10fa32-a0b8-4ae2-b92a-86ff857ab905
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: llm-d.ai/guide
            operator: In
            values:
            - pd-disaggregation
          - key: llm-d.ai/model
            operator: In
            values:
            - gpt-oss-120b
          - key: llm-d.ai/role
            operator: In
            values:
            - decode
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - openai/gpt-oss-120b
    - --disable-access-log-for-endpoints=/metrics,/health,/ping,/v1/models
    - --tensor-parallel-size=1
    - --block-size=128
    - --kv-transfer-config
    - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    - --no-disable-hybrid-kv-cache-manager
    - --gpu-memory-utilization=0.9
    command:
    - vllm
    - serve
    env:
    - name: VLLM_NIXL_SIDE_CHANNEL_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: HF_HOME
      value: /models
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: modelserver
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: modelserver
    ports:
    - containerPort: 8000
      name: modelserver
      protocol: TCP
    - containerPort: 5600
      name: nixl
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
      requests:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
    startupProbe:
      failureThreshold: 120
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
    - mountPath: /models
      name: model-cache
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: g1251ac
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pd-disaggregation-nvidia-gpu-vllm-sa
  serviceAccountName: pd-disaggregation-nvidia-gpu-vllm-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 20Gi
    name: shm
  - emptyDir: {}
    name: torch-compile-cache
  - emptyDir: {}
    name: vllm-config
  - emptyDir: {}
    name: triton-cache
  - name: model-cache
    persistentVolumeClaim:
      claimName: pd-disaggregation-nvidia-gpu-vllm-model-cache
status:
  allocatedResources:
    cpu: "8"
    memory: 16Gi
    nvidia.com/gpu: "1"
    rdma/ib: "1"
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-17T08:48:29Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-17T08:48:22Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-17T08:51:29Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-17T08:51:29Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-17T08:48:22Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "8"
      memory: 16Gi
      nvidia.com/gpu: "1"
      rdma/ib: "1"
    allocatedResourcesStatus:
    - name: nvidia.com/gpu
      resources:
      - health: Healthy
        resourceID: GPU-97fc723d-b540-e251-edee-c0115ff857e5
    - name: rdma/ib
      resources:
      - health: Healthy
        resourceID: "53"
    containerID: containerd://ce1eafbd2c1f35b2cdbf14bea258e22e40a10664f7fe4a999c75e1a66383249e
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer3
    imageID: ghcr.io/revit13/vllm-openai@sha256:fcb6ed6629e251d8388fc0e6a827fa31e4dd52db3d053ce1a2e2ad8d4fc4be34
    lastState: {}
    name: modelserver
    ready: true
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
      requests:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-17T08:48:30Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
    - mountPath: /models
      name: model-cache
  hostIP: 10.202.207.1
  hostIPs:
  - ip: 10.202.207.1
  observedGeneration: 1
  phase: Running
  podIP: 10.0.10.194
  podIPs:
  - ip: 10.0.10.194
  qosClass: Guaranteed
  resources:
    limits:
      cpu: "8"
      memory: 16Gi
    requests:
      cpu: 7990m
      memory: 16Gi
  startTime: "2026-07-17T08:48:22Z"
