apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-07-22T13:37:10Z"
  generateName: pd-disaggregation-nvidia-gpu-vllm-prefill-85f6865487-
  generation: 1
  labels:
    inference.networking.k8s.io/engine-type: vllm
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: pd-disaggregation
    llm-d.ai/model: gpt-oss-120b
    llm-d.ai/role: prefill
    pod-template-hash: 85f6865487
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "208"
  name: pd-disaggregation-nvidia-gpu-vllm-prefill-85f6865487-m82wb
  namespace: dpikus-pd-sglang-bench
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pd-disaggregation-nvidia-gpu-vllm-prefill-85f6865487
    uid: 2587d0aa-8961-4716-bbce-b598192e04b1
  resourceVersion: "36187485"
  uid: 779add52-e757-49d2-9951-c9b61f66ec7b
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            llm-d.ai/guide: pd-disaggregation
            llm-d.ai/role: decode
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - Qwen/Qwen3-VL-32B-Instruct
    - --disable-access-log-for-endpoints=/health,/metrics,/v1/models
    - --tensor-parallel-size=2
    - --block-size=128
    - --kv-transfer-config
    - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    - --no-disable-hybrid-kv-cache-manager
    - --gpu-memory-utilization=0.9
    - --load-format=runai_streamer
    command:
    - vllm
    - serve
    env:
    - name: HF_HUB_OFFLINE
      value: "1"
    - name: TRANSFORMERS_OFFLINE
      value: "1"
    - name: HF_HOME
      value: /model-cache
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          key: HF_TOKEN
          name: llm-d-hf-token
          optional: true
    - name: RUNAI_STREAMER_MEMORY_LIMIT
      value: "17179869184"
    - name: TRITON_CACHE_DIR
      value: /.triton-cache
    - name: VLLM_NIXL_SIDE_CHANNEL_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: modelserver
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: modelserver
    ports:
    - containerPort: 8000
      name: modelserver
      protocol: TCP
    - containerPort: 5600
      name: nixl
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "8"
        memory: 256Gi
        nvidia.com/gpu: "2"
        rdma/ib: "1"
      requests:
        cpu: "8"
        memory: 256Gi
        nvidia.com/gpu: "2"
        rdma/ib: "1"
    startupProbe:
      failureThreshold: 120
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /.triton-cache
      name: triton-cache
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: g134dfa
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pd-disaggregation-nvidia-gpu-vllm-sa
  serviceAccountName: pd-disaggregation-nvidia-gpu-vllm-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: model-cache
    persistentVolumeClaim:
      claimName: llm-d-model-cache
  - emptyDir:
      medium: Memory
      sizeLimit: 20Gi
    name: shm
  - emptyDir: {}
    name: torch-compile-cache
  - emptyDir: {}
    name: vllm-config
  - emptyDir: {}
    name: triton-cache
status:
  allocatedResources:
    cpu: "8"
    memory: 256Gi
    nvidia.com/gpu: "2"
    rdma/ib: "1"
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T13:37:19Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T13:37:11Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T13:40:18Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T13:40:18Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T13:37:10Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "8"
      memory: 256Gi
      nvidia.com/gpu: "2"
      rdma/ib: "1"
    allocatedResourcesStatus:
    - name: rdma/ib
      resources:
      - health: Healthy
        resourceID: "19"
    - name: nvidia.com/gpu
      resources:
      - health: Healthy
        resourceID: GPU-eeeec482-9c9e-1946-58ef-b613e4b021e1
      - health: Healthy
        resourceID: GPU-3912b228-49c6-ca6e-f52e-0d53ddcf8f6b
    containerID: containerd://f86feb0bb8eee4f80ba34f473a362641afac67919fa6c736b82d5e9068c70606
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imageID: ghcr.io/revit13/vllm-openai@sha256:ac60d4876f3eb8d888903b97bcc55bbbfd4a77d45f73155606f404358cccecab
    lastState: {}
    name: modelserver
    ready: true
    resources:
      limits:
        cpu: "8"
        memory: 256Gi
        nvidia.com/gpu: "2"
        rdma/ib: "1"
      requests:
        cpu: "8"
        memory: 256Gi
        nvidia.com/gpu: "2"
        rdma/ib: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-22T13:37:19Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /.triton-cache
      name: triton-cache
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
  hostIP: 10.202.208.155
  hostIPs:
  - ip: 10.202.208.155
  observedGeneration: 1
  phase: Running
  podIP: 10.0.9.16
  podIPs:
  - ip: 10.0.9.16
  qosClass: Guaranteed
  resources:
    limits:
      cpu: "8"
      memory: 256Gi
    requests:
      cpu: 7990m
      memory: 256Gi
  startTime: "2026-07-22T13:37:11Z"
