apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"model-cache-access","namespace":"alexey-sidecar-sglang"},"spec":{"containers":[{"command":["sleep","infinity"],"image":"busybox:1.36","name":"shell","resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/model-cache","name":"model-cache"}]}],"volumes":[{"name":"model-cache","persistentVolumeClaim":{"claimName":"llm-d-model-cache"}}]}}
  creationTimestamp: "2026-08-04T14:49:24Z"
  generation: 1
  labels:
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "214"
  name: model-cache-access
  namespace: alexey-sidecar-sglang
  resourceVersion: "49348199"
  uid: 2d5d7ff2-5546-48e1-8803-b49e99c57eda
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    name: shell
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gvbjw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: g49fc0a
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: model-cache
    persistentVolumeClaim:
      claimName: llm-d-model-cache
  - name: kube-api-access-gvbjw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: 100m
    memory: 128Mi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-08-04T14:49:34Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-08-04T14:49:24Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-08-04T14:49:34Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-08-04T14:49:34Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-08-04T14:49:24Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 100m
      memory: 128Mi
    containerID: containerd://a06c7abea085feaae0ba648149a18ea534d7e1a608dfeaa9c9c12b44674dc5c9
    image: docker.io/library/busybox:1.36
    imageID: docker.io/library/busybox@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
    lastState: {}
    name: shell
    ready: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-08-04T14:49:34Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 10
        uid: 0
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gvbjw
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.202.221.55
  hostIPs:
  - ip: 10.202.221.55
  observedGeneration: 1
  phase: Running
  podIP: 10.0.12.222
  podIPs:
  - ip: 10.0.12.222
  qosClass: Burstable
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 79m
      memory: 128Mi
  startTime: "2026-08-04T14:49:24Z"
