apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-08-19T06:57:50Z"
  generateName: pd-disaggregation-nvidia-gpu-vllm-decode-749c74d544-
  generation: 1
  labels:
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/engine-type: vllm
    llm-d.ai/guide: pd-disaggregation
    llm-d.ai/model: DeepSeek-V2
    llm-d.ai/role: decode
    pod-template-hash: 749c74d544
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "112"
  name: pd-disaggregation-nvidia-gpu-vllm-decode-749c74d544-8kx4h
  namespace: alexey-sidecar-sglang
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pd-disaggregation-nvidia-gpu-vllm-decode-749c74d544
    uid: ee18c2eb-192b-48c2-972e-4eabcdd22e88
  resourceVersion: "64519283"
  uid: 43932e30-32ca-46d5-9135-5c3eeb0ed17c
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              llm-d.ai/accelerator-variant: gpu
              llm-d.ai/accelerator-vendor: nvidia
              llm-d.ai/engine-type: vllm
              llm-d.ai/guide: pd-disaggregation
              llm-d.ai/model: DeepSeek-V2
              llm-d.ai/role: decode
          topologyKey: kubernetes.io/hostname
        weight: 100
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            llm-d.ai/accelerator-variant: gpu
            llm-d.ai/accelerator-vendor: nvidia
            llm-d.ai/engine-type: vllm
            llm-d.ai/guide: pd-disaggregation
            llm-d.ai/model: DeepSeek-V2
            llm-d.ai/role: prefill
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - deepseek-ai/DeepSeek-V2
    - --disable-access-log-for-endpoints=/health,/metrics,/v1/models
    - --tensor-parallel-size=4
    - --block-size=128
    - --max-model-len=32000
    - --kv-transfer-config
    - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    - --load-format=runai_streamer
    - --model-loader-extra-config
    - '{"distributed":true,"concurrency":16,"memory_limit":17179869184}'
    - --no-disable-hybrid-kv-cache-manager
    - --port=8200
    command:
    - vllm
    - serve
    env:
    - name: HF_HOME
      value: /model-cache
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          key: HF_TOKEN
          name: llm-d-hf-token
    - name: VLLM_NIXL_SIDE_CHANNEL_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: USER
      value: llm-d
    - name: UCX_MODULE_DIR
      value: /usr/local/lib/python3.12/dist-packages/nixl_cu13.libs/ucx
    image: vllm/vllm-openai:v0.23.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: modelserver
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: modelserver
    ports:
    - containerPort: 8200
      name: modelserver
      protocol: TCP
    - containerPort: 5600
      name: nixl
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "16"
        memory: 400Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 400Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
    startupProbe:
      failureThreshold: 120
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - --port=8000
    - --vllm-port=8200
    - --kv-connector=nixlv2
    - --zap-log-level=1
    - --secure-proxy=false
    image: ghcr.io/llm-d/llm-d-router-disagg-sidecar:main
    imagePullPolicy: Always
    name: routing-proxy
    ports:
    - containerPort: 8000
      name: sidecar
      protocol: TCP
    resources: {}
    restartPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: g124daa
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pd-disaggregation-nvidia-gpu-vllm-sa
  serviceAccountName: pd-disaggregation-nvidia-gpu-vllm-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: model-cache
    persistentVolumeClaim:
      claimName: llm-d-model-cache
  - emptyDir:
      medium: Memory
      sizeLimit: 20Gi
    name: shm
  - emptyDir: {}
    name: torch-compile-cache
  - emptyDir: {}
    name: vllm-config
  - emptyDir: {}
    name: triton-cache
status:
  allocatedResources:
    cpu: "16"
    memory: 400Gi
    nvidia.com/gpu: "4"
    rdma/ib: "1"
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-08-19T06:58:01Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-08-19T06:58:02Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-08-19T07:01:31Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-08-19T07:01:31Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-08-19T06:57:50Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "16"
      memory: 400Gi
      nvidia.com/gpu: "4"
      rdma/ib: "1"
    allocatedResourcesStatus:
    - name: nvidia.com/gpu
      resources:
      - health: Healthy
        resourceID: GPU-60cf86ca-7deb-1e26-5047-73d52874eb8c
      - health: Healthy
        resourceID: GPU-d0e3ac83-8bd7-3e98-d962-eebfc64dde11
      - health: Healthy
        resourceID: GPU-199abc11-53b6-29dc-f85c-a1dc1e123f1d
      - health: Healthy
        resourceID: GPU-b6aed796-ed34-2dde-4a69-bb9e7ce1e868
    - name: rdma/ib
      resources:
      - health: Healthy
        resourceID: "38"
    containerID: containerd://e81c0232a6afcd1d0cc3707a0fcd6235707d2d8eb4ae2118361dcc8d0a0b6508
    image: docker.io/vllm/vllm-openai:v0.23.0
    imageID: docker.io/vllm/vllm-openai@sha256:6d8429e38e3747723ca07ee1b17972e09bb9c51c4032b266f24fb1cc3b22ed8f
    lastState: {}
    name: modelserver
    ready: true
    resources:
      limits:
        cpu: "16"
        memory: 400Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 400Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-08-19T06:58:02Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /model-cache
      name: model-cache
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
  hostIP: 10.202.210.33
  hostIPs:
  - ip: 10.202.210.33
  initContainerStatuses:
  - containerID: containerd://5f1018d20e80d95813d75e6ea29b392f7a90a58a7ea610bbc0ebf0850a2d303d
    image: ghcr.io/llm-d/llm-d-router-disagg-sidecar:main
    imageID: ghcr.io/llm-d/llm-d-router-disagg-sidecar@sha256:fcb85926e2dc5e60dfbcde57a11552d6e61224ab02585b5e80021ae890cad0b9
    lastState: {}
    name: routing-proxy
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-08-19T06:58:02Z"
    user:
      linux:
        gid: 65532
        supplementalGroups:
        - 65532
        uid: 65532
  observedGeneration: 1
  phase: Running
  podIP: 10.0.6.67
  podIPs:
  - ip: 10.0.6.67
  qosClass: Burstable
  resources:
    limits:
      cpu: "16"
      memory: 400Gi
    requests:
      cpu: 15978m
      memory: 400Gi
  startTime: "2026-08-19T06:57:50Z"
