apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "multi-nic-compute",
          "namespace": "openshift-sriov-network-operator"
        }
      ]
    kubectl.kubernetes.io/restartedAt: "2026-07-06T16:08:31+03:00"
  creationTimestamp: "2026-07-18T17:22:50Z"
  generateName: epd-nvidia-gpu-vllm-prefill-5678f54fb4-
  generation: 1
  labels:
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: epd
    llm-d.ai/model: Qwen3-VL-2B-Instruct
    llm-d.ai/role: prefill
    pod-template-hash: 5678f54fb4
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "163"
  name: epd-nvidia-gpu-vllm-prefill-5678f54fb4-mdpcq
  namespace: dpikus-epd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: epd-nvidia-gpu-vllm-prefill-5678f54fb4
    uid: 282165f0-08a3-4260-be1c-60b5f4841e82
  resourceVersion: "32352957"
  uid: a01dd7ff-2495-48a5-9918-a9fdab4a1078
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: llm-d.ai/guide
            operator: In
            values:
            - epd
          - key: llm-d.ai/model
            operator: In
            values:
            - Qwen3-VL-2B-Instruct
          - key: llm-d.ai/role
            operator: In
            values:
            - decode
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - --model
    - openai/gpt-oss-120b
    - --port
    - "8000"
    - --tensor-parallel-size
    - "1"
    - --block-size
    - "128"
    - --kv-transfer-config
    - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    - --disable-access-log-for-endpoints=/health,/metrics,/v1/models
    - --no-disable-hybrid-kv-cache-manager
    - --gpu-memory-utilization=0.9
    command:
    - vllm
    - serve
    env:
    - name: VLLM_LOGGING_LEVEL
      value: INFO
    - name: VLLM_NIXL_SIDE_CHANNEL_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: DP_SIZE
      value: "1"
    - name: TP_SIZE
      value: "1"
    - name: DP_SIZE_LOCAL
      value: "1"
    - name: HF_HOME
      value: /model-cache
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          key: HF_TOKEN
          name: llm-d-hf-token
          optional: true
    - name: TRITON_CACHE_DIR
      value: /.triton-cache
    - name: HF_HUB_OFFLINE
      value: "1"
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: modelserver
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: modelserver
    ports:
    - containerPort: 5600
      name: nixl
      protocol: TCP
    - containerPort: 8000
      name: modelserver
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
      requests:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
    startupProbe:
      failureThreshold: 120
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.triton-cache
      name: triton-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /model-cache
      name: model-cache
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gc37d06
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: epd-nvidia-gpu-vllm-sa
  serviceAccountName: epd-nvidia-gpu-vllm-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 20Gi
    name: shm
  - emptyDir: {}
    name: torch-compile-cache
  - emptyDir: {}
    name: triton-cache
  - emptyDir: {}
    name: vllm-config
  - name: model-cache
    persistentVolumeClaim:
      claimName: llm-d-model-cache
status:
  allocatedResources:
    cpu: "8"
    memory: 16Gi
    nvidia.com/gpu: "1"
    rdma/ib: "1"
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-18T17:22:58Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-18T17:22:51Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-18T17:25:58Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-18T17:25:58Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-18T17:22:50Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "8"
      memory: 16Gi
      nvidia.com/gpu: "1"
      rdma/ib: "1"
    allocatedResourcesStatus:
    - name: rdma/ib
      resources:
      - health: Healthy
        resourceID: "42"
    - name: nvidia.com/gpu
      resources:
      - health: Healthy
        resourceID: GPU-97d4cfea-6c69-86c4-b360-217df6345285
    containerID: containerd://6e4f17a6d725862726a37cb0ba5f2d6f658c02b50e4683c07106b6a85fafda21
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imageID: ghcr.io/revit13/vllm-openai@sha256:ac60d4876f3eb8d888903b97bcc55bbbfd4a77d45f73155606f404358cccecab
    lastState: {}
    name: modelserver
    ready: true
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
      requests:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
        rdma/ib: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-18T17:22:59Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.triton-cache
      name: triton-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /model-cache
      name: model-cache
  hostIP: 10.202.208.5
  hostIPs:
  - ip: 10.202.208.5
  observedGeneration: 1
  phase: Running
  podIP: 10.0.5.181
  podIPs:
  - ip: 10.0.5.181
  qosClass: Guaranteed
  resources:
    limits:
      cpu: "8"
      memory: 16Gi
    requests:
      cpu: 7990m
      memory: 16Gi
  startTime: "2026-07-18T17:22:51Z"
