apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2026-07-07T07:47:58Z","generation":6,"labels":{"inference.networking.k8s.io/engine-type":"vllm","llm-d.ai/accelerator-variant":"gpu","llm-d.ai/accelerator-vendor":"nvidia","llm-d.ai/guide":"pd-disaggregation","llm-d.ai/model":"gpt-oss-120b","llm-d.ai/role":"decode"},"name":"pd-disaggregation-nvidia-gpu-vllm-decode","namespace":"dpikus-pd","resourceVersion":"22974788","uid":"833f8c0f-b520-4644-b520-0b2c0455dd60"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"inference.networking.k8s.io/engine-type":"vllm","llm-d.ai/accelerator-variant":"gpu","llm-d.ai/accelerator-vendor":"nvidia","llm-d.ai/guide":"pd-disaggregation","llm-d.ai/model":"gpt-oss-120b","llm-d.ai/role":"decode"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"inference.networking.k8s.io/engine-type":"vllm","llm-d.ai/accelerator-variant":"gpu","llm-d.ai/accelerator-vendor":"nvidia","llm-d.ai/guide":"pd-disaggregation","llm-d.ai/model":"gpt-oss-120b","llm-d.ai/role":"decode"}},"spec":{"containers":[{"args":["openai/gpt-oss-120b","--disable-access-log-for-endpoints=/health,/metrics,/v1/models","--tensor-parallel-size=4","--block-size=128","--kv-transfer-config","{\"kv_connector\":\"NixlConnector\", \"kv_role\":\"kv_both\"}","--disable-access-log-for-endpoints /metrics,/health,/ping","--no-disable-hybrid-kv-cache-manager","--port=8200"],"command":["vllm","serve"],"env":[{"name":"VLLM_NIXL_SIDE_CHANNEL_HOST","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.podIP"}}},{"name":"HF_HOME","value":"/models"}],"image":"ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer3","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":"modelserver","scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"modelserver","ports":[{"containerPort":8200,"name":"modelserver","protocol":"TCP"},{"containerPort":5600,"name":"nixl","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/v1/models","port":"modelserver","scheme":"HTTP"},"periodSeconds":5,"successThreshold":1,"timeoutSeconds":2},"resources":{"limits":{"cpu":"16","memory":"64Gi","nvidia.com/gpu":"4","rdma/ib":"1"},"requests":{"cpu":"16","memory":"64Gi","nvidia.com/gpu":"4","rdma/ib":"1"}},"startupProbe":{"failureThreshold":120,"httpGet":{"path":"/v1/models","port":"modelserver","scheme":"HTTP"},"initialDelaySeconds":15,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":5},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/dev/shm","name":"shm"},{"mountPath":"/.cache","name":"torch-compile-cache"},{"mountPath":"/.config","name":"vllm-config"},{"mountPath":"/.triton","name":"triton-cache"},{"mountPath":"/models","name":"model-cache"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"args":["--port=8000","--vllm-port=8200","--connector=nixlv2","--zap-log-level=1","--secure-proxy=false"],"image":"ghcr.io/roytman/llm-d-inference-scheduler/llm-d-router-disagg-sidecar:dev","imagePullPolicy":"Always","name":"routing-proxy","ports":[{"containerPort":8000,"name":"sidecar","protocol":"TCP"}],"resources":{},"restartPolicy":"Always","securityContext":{"allowPrivilegeEscalation":false,"runAsNonRoot":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"pd-disaggregation-nvidia-gpu-vllm-sa","serviceAccountName":"pd-disaggregation-nvidia-gpu-vllm-sa","terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{"medium":"Memory","sizeLimit":"20Gi"},"name":"shm"},{"emptyDir":{},"name":"torch-compile-cache"},{"emptyDir":{},"name":"vllm-config"},{"emptyDir":{},"name":"triton-cache"},{"name":"model-cache","persistentVolumeClaim":{"claimName":"pd-disaggregation-nvidia-gpu-vllm-model-cache"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2026-07-07T07:47:58Z","lastUpdateTime":"2026-07-07T14:16:03Z","message":"ReplicaSet \"pd-disaggregation-nvidia-gpu-vllm-decode-664f69475f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2026-07-09T09:01:01Z","lastUpdateTime":"2026-07-09T09:01:01Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":6,"readyReplicas":1,"replicas":1,"terminatingReplicas":0,"updatedReplicas":1}}
  creationTimestamp: "2026-07-07T07:47:58Z"
  generation: 99
  labels:
    inference.networking.k8s.io/engine-type: vllm
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: pd-disaggregation
    llm-d.ai/model: gpt-oss-120b
    llm-d.ai/role: decode
  name: pd-disaggregation-nvidia-gpu-vllm-decode
  namespace: dpikus-pd
  resourceVersion: "35016401"
  uid: 833f8c0f-b520-4644-b520-0b2c0455dd60
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      inference.networking.k8s.io/engine-type: vllm
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: nvidia
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/model: gpt-oss-120b
      llm-d.ai/role: decode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gpu-reaper.io/exclude: "True"
      labels:
        inference.networking.k8s.io/engine-type: vllm
        llm-d.ai/accelerator-variant: gpu
        llm-d.ai/accelerator-vendor: nvidia
        llm-d.ai/guide: pd-disaggregation
        llm-d.ai/model: gpt-oss-120b
        llm-d.ai/role: decode
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: llm-d.ai/guide
                operator: In
                values:
                - pd-disaggregation
              - key: llm-d.ai/model
                operator: In
                values:
                - gpt-oss-120b
              - key: llm-d.ai/role
                operator: In
                values:
                - prefill
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - openai/gpt-oss-120b
        - --disable-access-log-for-endpoints=/metrics,/health,/ping,/v1/models
        - --tensor-parallel-size=4
        - --block-size=128
        - --kv-transfer-config
        - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
        - --no-disable-hybrid-kv-cache-manager
        - --port=8200
        command:
        - vllm
        - serve
        env:
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HF_HOME
          value: /models
        image: vllm/vllm-openai:v0.23.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: modelserver
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: modelserver
        ports:
        - containerPort: 8200
          name: modelserver
          protocol: TCP
        - containerPort: 5600
          name: nixl
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/models
            port: modelserver
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "16"
            memory: 64Gi
            nvidia.com/gpu: "4"
            rdma/ib: "1"
          requests:
            cpu: "16"
            memory: 64Gi
            nvidia.com/gpu: "4"
            rdma/ib: "1"
        startupProbe:
          failureThreshold: 120
          httpGet:
            path: /v1/models
            port: modelserver
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /.cache
          name: torch-compile-cache
        - mountPath: /.config
          name: vllm-config
        - mountPath: /.triton
          name: triton-cache
        - mountPath: /models
          name: model-cache
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --port=8000
        - --vllm-port=8200
        - --connector=nixlv2
        - --zap-log-level=1
        - --secure-proxy=false
        image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.8.0
        imagePullPolicy: Always
        name: routing-proxy
        ports:
        - containerPort: 8000
          name: sidecar
          protocol: TCP
        resources: {}
        restartPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        kubernetes.io/hostname: gf2a19e
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pd-disaggregation-nvidia-gpu-vllm-sa
      serviceAccountName: pd-disaggregation-nvidia-gpu-vllm-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 20Gi
        name: shm
      - emptyDir: {}
        name: torch-compile-cache
      - emptyDir: {}
        name: vllm-config
      - emptyDir: {}
        name: triton-cache
      - name: model-cache
        persistentVolumeClaim:
          claimName: pd-disaggregation-nvidia-gpu-vllm-model-cache
status:
  conditions:
  - lastTransitionTime: "2026-07-21T09:11:02Z"
    lastUpdateTime: "2026-07-21T09:11:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-07-09T15:55:29Z"
    lastUpdateTime: "2026-07-21T09:11:02Z"
    message: ReplicaSet "pd-disaggregation-nvidia-gpu-vllm-decode-5485494c48" has
      successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 99
  terminatingReplicas: 0
