apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-07-07T07:47:58Z"
  generateName: pd-disaggregation-nvidia-gpu-vllm-decode-6b74ff7fb8-
  generation: 1
  labels:
    inference.networking.k8s.io/engine-type: vllm
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: pd-disaggregation
    llm-d.ai/model: gpt-oss-120b
    llm-d.ai/role: decode
    pod-template-hash: 6b74ff7fb8
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "217"
  name: pd-disaggregation-nvidia-gpu-vllm-decode-6b74ff7fb8-cgbhj
  namespace: dpikus-pd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pd-disaggregation-nvidia-gpu-vllm-decode-6b74ff7fb8
    uid: 07ad94e7-e87e-41c9-8a32-491a10bb8f64
  resourceVersion: "21041477"
  uid: 521190e2-5593-443d-bea0-3072e39da2f5
spec:
  containers:
  - args:
    - openai/gpt-oss-120b
    - --disable-access-log-for-endpoints=/health,/metrics,/v1/models
    - --tensor-parallel-size=4
    - --block-size=128
    - --kv-transfer-config
    - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    - --no-disable-hybrid-kv-cache-manager
    - --port=8200
    command:
    - vllm
    - serve
    env:
    - name: VLLM_NIXL_SIDE_CHANNEL_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: HF_HOME
      value: /models
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: modelserver
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: modelserver
    ports:
    - containerPort: 8200
      name: modelserver
      protocol: TCP
    - containerPort: 5600
      name: nixl
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "16"
        memory: 64Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 64Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
    startupProbe:
      failureThreshold: 120
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
    - mountPath: /models
      name: model-cache
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - --port=8000
    - --vllm-port=8200
    - --connector=nixlv2
    - --zap-log-level=1
    - --secure-proxy=false
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.8.0
    imagePullPolicy: Always
    name: routing-proxy
    ports:
    - containerPort: 8000
      name: sidecar
      protocol: TCP
    resources: {}
    restartPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: g12987a
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pd-disaggregation-nvidia-gpu-vllm-sa
  serviceAccountName: pd-disaggregation-nvidia-gpu-vllm-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 20Gi
    name: shm
  - emptyDir: {}
    name: torch-compile-cache
  - emptyDir: {}
    name: vllm-config
  - emptyDir: {}
    name: triton-cache
  - name: model-cache
    persistentVolumeClaim:
      claimName: pd-disaggregation-nvidia-gpu-vllm-model-cache
status:
  allocatedResources:
    cpu: "16"
    memory: 64Gi
    nvidia.com/gpu: "4"
    rdma/ib: "1"
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-07T07:48:06Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-07T07:48:06Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-07T07:53:05Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-07T07:53:05Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-07T07:48:01Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "16"
      memory: 64Gi
      nvidia.com/gpu: "4"
      rdma/ib: "1"
    allocatedResourcesStatus:
    - name: nvidia.com/gpu
      resources:
      - health: Healthy
        resourceID: GPU-96ee6158-5dce-fa70-0ade-a2430af73147
      - health: Healthy
        resourceID: GPU-df7945f9-52d2-7bd3-24ae-831b2bc8ee0a
      - health: Healthy
        resourceID: GPU-b01453bc-9d4f-5eb0-201a-ae142a349c89
      - health: Healthy
        resourceID: GPU-40ba46db-ff43-fe77-5cef-ea60ce598f60
    - name: rdma/ib
      resources:
      - health: Healthy
        resourceID: "9"
    containerID: containerd://f0e1f5aa2b4ed39d62cdef478d28fea3c5c1701954f92457a236a69041c0c52b
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer3
    imageID: ghcr.io/revit13/vllm-openai@sha256:fcb6ed6629e251d8388fc0e6a827fa31e4dd52db3d053ce1a2e2ad8d4fc4be34
    lastState: {}
    name: modelserver
    ready: true
    resources:
      limits:
        cpu: "16"
        memory: 64Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 64Gi
        nvidia.com/gpu: "4"
        rdma/ib: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-07T07:48:08Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /.triton
      name: triton-cache
    - mountPath: /models
      name: model-cache
  hostIP: 10.202.208.181
  hostIPs:
  - ip: 10.202.208.181
  initContainerStatuses:
  - containerID: containerd://c2c944d34f30f11690e7d819818773a295d4e9208d4554537a71faea0060bfdd
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.8.0
    imageID: ghcr.io/llm-d/llm-d-routing-sidecar@sha256:d49dd8d7d6a15a4ef82f3aaa322783ebaead2bf9fc9cdb4d375da0da12bf0147
    lastState: {}
    name: routing-proxy
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-07T07:48:06Z"
    user:
      linux:
        gid: 65532
        supplementalGroups:
        - 65532
        uid: 65532
  observedGeneration: 1
  phase: Running
  podIP: 10.0.10.74
  podIPs:
  - ip: 10.0.10.74
  qosClass: Burstable
  resources:
    limits:
      cpu: "16"
      memory: 64Gi
    requests:
      cpu: 15978m
      memory: 64Gi
  startTime: "2026-07-07T07:48:01Z"
