apiVersion: v1
data:
  coordinator.yaml: |
    log_level: 2
    server:
      listen_addr: ":8080"
      read_timeout: 30s
      write_timeout: 120s

    gateway:
      address: "http://llm-d-inference-gateway-istio.alexey-epd-sglang-bench.svc:80"
      max_idle_conns_per_host: 1000
      idle_conn_timeout: 300s
      timeout: 600s

    pipeline:
      kv_connector: kv-nixl
      steps:
        - type: prefill
        - type: decode
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"coordinator.yaml":"log_level: 2\nserver:\n  listen_addr: \":8080\"\n  read_timeout: 30s\n  write_timeout: 120s\n\ngateway:\n  address: \"http://llm-d-inference-gateway-istio.alexey-epd-sglang-bench.svc:80\"\n  max_idle_conns_per_host: 1000\n  idle_conn_timeout: 300s\n  timeout: 600s\n\npipeline:\n  kv_connector: kv-nixl\n  steps:\n    - type: prefill\n    - type: decode\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"llm-d-coordinator-config","namespace":"alexey-epd-sglang-bench"}}
  creationTimestamp: "2026-08-03T08:47:18Z"
  name: llm-d-coordinator-config
  namespace: alexey-epd-sglang-bench
  resourceVersion: "61851959"
  uid: 5675d385-8c96-49b0-9e4e-e904156167c3
