apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-07-22T10:56:40Z"
  generateName: sglang-bench-
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: 23270d2d-cc8f-4da2-ad8e-e66485ad12ca
    batch.kubernetes.io/job-name: sglang-bench
    controller-uid: 23270d2d-cc8f-4da2-ad8e-e66485ad12ca
    job-name: sglang-bench
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "185"
  name: sglang-bench-bvnd9
  namespace: dpikus-epd-sglang-bench
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: sglang-bench
    uid: 23270d2d-cc8f-4da2-ad8e-e66485ad12ca
  resourceVersion: "36070663"
  uid: b1eef19c-230b-4189-ac96-914a78e99161
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - turin-gp
  containers:
  - command:
    - /bin/bash
    - /scripts/run_bench.sh
    env:
    - name: GATEWAY_IP
      value: llm-d-inference-gateway-istio
    image: docker.io/lmsysorg/sglang:v0.5.14
    imagePullPolicy: IfNotPresent
    name: bench
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
      requests:
        cpu: "4"
        memory: 8Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts
      name: script
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2t99n
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: g801c7a
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 493
      name: sglang-bench-script
    name: script
  - name: kube-api-access-2t99n
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: "4"
    memory: 8Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T11:16:40Z"
    observedGeneration: 1
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T10:56:40Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T11:16:39Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T11:16:39Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-22T10:56:40Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "4"
      memory: 8Gi
    containerID: containerd://c18dd738544c7e62aa9602bead9c12e3a295338cf982fc25c6b707c0eada7301
    image: docker.io/lmsysorg/sglang:v0.5.14
    imageID: docker.io/lmsysorg/sglang@sha256:5027e95bf6ec536856b1b52a91d1f35ff5c564ab83e8a94758a169ff09bb8df3
    lastState: {}
    name: bench
    ready: false
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
      requests:
        cpu: "4"
        memory: 8Gi
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://c18dd738544c7e62aa9602bead9c12e3a295338cf982fc25c6b707c0eada7301
        exitCode: 0
        finishedAt: "2026-07-22T11:16:38Z"
        reason: Completed
        startedAt: "2026-07-22T10:56:41Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /scripts
      name: script
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2t99n
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.202.212.51
  hostIPs:
  - ip: 10.202.212.51
  observedGeneration: 1
  phase: Succeeded
  podIP: 10.0.12.57
  podIPs:
  - ip: 10.0.12.57
  qosClass: Burstable
  resources:
    limits:
      cpu: "8"
      memory: 16Gi
    requests:
      cpu: 3996m
      memory: 8Gi
  startTime: "2026-07-22T10:56:40Z"
