apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-07-06T15:41:02Z"
  generateName: reqsend-long-b85d68496-
  generation: 1
  labels:
    app: reqsend-long
    pod-template-hash: b85d68496
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "185"
  name: reqsend-long-b85d68496-5d8tm
  namespace: dpikus-epd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: reqsend-long-b85d68496
    uid: c66b10db-bf49-4247-89ee-c4ac19a8f6fc
  resourceVersion: "20274459"
  uid: 6881582e-e024-4350-ba7f-a06642483a0d
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: golang:1.24
    imagePullPolicy: IfNotPresent
    name: reqsend
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /work
      name: src
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wnxcm
      readOnly: true
    workingDir: /work
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: g801c7a
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: reqsend-long-src
    name: src
  - name: kube-api-access-wnxcm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-06T15:41:03Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-06T15:41:02Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-06T15:41:03Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-06T15:41:03Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-06T15:41:02Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://55a19c85e2cda612096ab70d9bfe25b4100def0fec10b0db49e5bb55f9748d9f
    image: docker.io/library/golang:1.24
    imageID: docker.io/library/golang@sha256:d2d2bc1c84f7e60d7d2438a3836ae7d0c847f4888464e7ec9ba3a1339a1ee804
    lastState: {}
    name: reqsend
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-06T15:41:03Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /work
      name: src
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wnxcm
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.202.212.51
  hostIPs:
  - ip: 10.202.212.51
  observedGeneration: 1
  phase: Running
  podIP: 10.0.12.20
  podIPs:
  - ip: 10.0.12.20
  qosClass: BestEffort
  resources: {}
  startTime: "2026-07-06T15:41:02Z"
