apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "multi-nic-compute",
          "namespace": "openshift-sriov-network-operator"
        }
      ]
  creationTimestamp: "2026-07-19T09:31:21Z"
  generateName: epd-nvidia-gpu-vllm-decode-787587f6bd-
  generation: 1
  labels:
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: epd
    llm-d.ai/model: Qwen3-VL-2B-Instruct
    llm-d.ai/role: decode
    pod-template-hash: 787587f6bd
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "112"
  name: epd-nvidia-gpu-vllm-decode-787587f6bd-p5jmm
  namespace: dpikus-epd-sglang-bench
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: epd-nvidia-gpu-vllm-decode-787587f6bd
    uid: 2c4f14a2-cd0f-4296-80f5-3f0744728364
  resourceVersion: "33103958"
  uid: 451c9134-4543-4036-91c4-c102071a8b9c
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            llm-d.ai/guide: epd
            llm-d.ai/role: prefill
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - --model
    - Qwen/Qwen3-VL-235B-A22B-Instruct
    - --port
    - "8000"
    - --tensor-parallel-size
    - "8"
    - --block-size
    - "128"
    - --kv-transfer-config
    - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    - --disable-access-log-for-endpoints=/health,/metrics,/v1/models
    - --no-disable-hybrid-kv-cache-manager
    - --load-format=runai_streamer
    command:
    - vllm
    - serve
    env:
    - name: HF_HUB_OFFLINE
      value: "1"
    - name: TRANSFORMERS_OFFLINE
      value: "1"
    - name: VLLM_LOGGING_LEVEL
      value: INFO
    - name: VLLM_NIXL_SIDE_CHANNEL_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: DP_SIZE
      value: "1"
    - name: TP_SIZE
      value: "8"
    - name: DP_SIZE_LOCAL
      value: "1"
    - name: HF_HOME
      value: /model-cache
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          key: HF_TOKEN
          name: llm-d-hf-token
          optional: true
    - name: RUNAI_STREAMER_MEMORY_LIMIT
      value: "17179869184"
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: modelserver
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: modelserver
    ports:
    - containerPort: 5600
      name: nixl
      protocol: TCP
    - containerPort: 8000
      name: modelserver
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
    startupProbe:
      failureThreshold: 120
      httpGet:
        path: /v1/models
        port: modelserver
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.triton
      name: triton-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /model-cache
      name: model-cache
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: g124daa
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: epd-nvidia-gpu-vllm-sa
  serviceAccountName: epd-nvidia-gpu-vllm-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 20Gi
    name: shm
  - emptyDir: {}
    name: torch-compile-cache
  - emptyDir: {}
    name: triton-cache
  - emptyDir: {}
    name: vllm-config
  - name: model-cache
    persistentVolumeClaim:
      claimName: llm-d-model-cache
status:
  allocatedResources:
    cpu: "16"
    memory: 256Gi
    nvidia.com/gpu: "8"
    rdma/ib: "1"
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T09:31:31Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T09:31:21Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T09:42:30Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T09:42:30Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-19T09:31:21Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "16"
      memory: 256Gi
      nvidia.com/gpu: "8"
      rdma/ib: "1"
    allocatedResourcesStatus:
    - name: rdma/ib
      resources:
      - health: Healthy
        resourceID: "52"
    - name: nvidia.com/gpu
      resources:
      - health: Healthy
        resourceID: GPU-199abc11-53b6-29dc-f85c-a1dc1e123f1d
      - health: Healthy
        resourceID: GPU-47f0e455-ff2c-b98e-ddef-69c0b957648b
      - health: Healthy
        resourceID: GPU-469aa5e2-d283-7a6e-ecbc-0a286fc0f463
      - health: Healthy
        resourceID: GPU-c27f71d8-6f25-4a59-ede6-6055b49ec3c9
      - health: Healthy
        resourceID: GPU-b6aed796-ed34-2dde-4a69-bb9e7ce1e868
      - health: Healthy
        resourceID: GPU-60cf86ca-7deb-1e26-5047-73d52874eb8c
      - health: Healthy
        resourceID: GPU-d0e3ac83-8bd7-3e98-d962-eebfc64dde11
      - health: Healthy
        resourceID: GPU-b6d1a8a8-c117-d3f9-9300-2288a1a09e05
    containerID: containerd://661f20cb4b99f5782e8be82805704546c4ce60e955b8629abe62ed14a5212545
    image: ghcr.io/revit13/vllm-openai:nightly-b50646e5effd7cb5884cd96fdff4c53c18521198.omer4
    imageID: ghcr.io/revit13/vllm-openai@sha256:ac60d4876f3eb8d888903b97bcc55bbbfd4a77d45f73155606f404358cccecab
    lastState: {}
    name: modelserver
    ready: true
    resources:
      limits:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
      requests:
        cpu: "16"
        memory: 256Gi
        nvidia.com/gpu: "8"
        rdma/ib: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-19T09:31:31Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /.cache
      name: torch-compile-cache
    - mountPath: /.triton
      name: triton-cache
    - mountPath: /.config
      name: vllm-config
    - mountPath: /model-cache
      name: model-cache
  hostIP: 10.202.210.33
  hostIPs:
  - ip: 10.202.210.33
  observedGeneration: 1
  phase: Running
  podIP: 10.0.6.61
  podIPs:
  - ip: 10.0.6.61
  qosClass: Guaranteed
  resources:
    limits:
      cpu: "16"
      memory: 256Gi
    requests:
      cpu: 15978m
      memory: 256Gi
  startTime: "2026-07-19T09:31:21Z"
