apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-08-15T20:06:27Z"
  generateName: sglang-bench-
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: 4080ae17-a166-40d2-ab17-bfac5c9ed1ec
    batch.kubernetes.io/job-name: sglang-bench
    controller-uid: 4080ae17-a166-40d2-ab17-bfac5c9ed1ec
    job-name: sglang-bench
    topology.kubernetes.io/region: US-EAST-01
    topology.kubernetes.io/zone: "199"
  name: sglang-bench-k2jmm
  namespace: alexey-sidecar-sglang
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: sglang-bench
    uid: 4080ae17-a166-40d2-ab17-bfac5c9ed1ec
  resourceVersion: "61097141"
  uid: 6f9cb712-787c-41a1-98a3-aedbd001be68
spec:
  containers:
  - command:
    - /bin/bash
    - /scripts/run_bench.sh
    env:
    - name: GATEWAY_IP
      value: llm-d-inference-gateway-istio
    image: docker.io/lmsysorg/sglang:v0.5.14
    imagePullPolicy: IfNotPresent
    name: bench
    resources:
      limits:
        cpu: "8"
        memory: 32Gi
      requests:
        cpu: "8"
        memory: 32Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts
      name: script
    - mountPath: /results
      name: results
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h88rl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gd86486
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 493
      name: sglang-bench-script
    name: script
  - name: results
    persistentVolumeClaim:
      claimName: llm-d-model-cache
  - name: kube-api-access-h88rl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: "8"
    memory: 32Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-08-15T20:34:25Z"
    observedGeneration: 1
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-08-15T20:06:27Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-08-15T20:34:24Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-08-15T20:34:24Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-08-15T20:06:27Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "8"
      memory: 32Gi
    containerID: containerd://d1e9e12b326fee5fe99a710a7fe362100be18b99dd86888827c5dc4f85a7db4b
    image: docker.io/lmsysorg/sglang:v0.5.14
    imageID: docker.io/lmsysorg/sglang@sha256:5027e95bf6ec536856b1b52a91d1f35ff5c564ab83e8a94758a169ff09bb8df3
    lastState: {}
    name: bench
    ready: false
    resources:
      limits:
        cpu: "8"
        memory: 32Gi
      requests:
        cpu: "8"
        memory: 32Gi
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://d1e9e12b326fee5fe99a710a7fe362100be18b99dd86888827c5dc4f85a7db4b
        exitCode: 0
        finishedAt: "2026-08-15T20:34:23Z"
        reason: Completed
        startedAt: "2026-08-15T20:06:33Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /scripts
      name: script
    - mountPath: /results
      name: results
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h88rl
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.202.220.223
  hostIPs:
  - ip: 10.202.220.223
  observedGeneration: 1
  phase: Succeeded
  podIP: 10.0.15.174
  podIPs:
  - ip: 10.0.15.174
  qosClass: Guaranteed
  resources:
    limits:
      memory: 32Gi
    requests:
      cpu: 7990m
      memory: 32Gi
  startTime: "2026-08-15T20:06:27Z"
